### ISSUE TITLE
table value typo

### ISSUE THREAD

**Issue by nicholustintzaw** [como-ph/oxcgrt#47]
There is a typo error about the SMART criteria cut-off point for skewness/kurtosis in "Article called Distributions of variables and indices". 
The cut-off point for "acceptable" was mentioned as "≥ 0.6 and < 0.6". Actually, it should be ">=0.4 and <0.6". You can see in the table name "The range of absolute values of skewness and kurtosis statistics that are applied by SMART (2015)" under sub-topic called "Skew and kurtosis".

**Comment by ernestguevarra** [comment]
I think this is the wrong repo to post this issue @nicholustintzaw. I think you should post this to the `nutricheckr/nipnTK` repository.
